PRESET_BLUEPRINTS = [
    {
        "name": "Siedeln Route — Standard",
        "tribe": "alle",
        "description": "Klassische Siedeln-Route für einen effizienten Start ins Runde. Ziel: 3. Dorf so schnell wie möglich.",
        "steps": [
            {"step": 1, "title": "Das erste Abenteuer machen", "target": "", "notes": ""},
            {"step": 2, "title": "1x Lehmgrube", "target": "Level 2", "notes": "von 1 auf 2"},
            {"step": 3, "title": "1x Eisenmine", "target": "Level 2", "notes": ""},
            {"step": 4, "title": "1x Rohstofflager", "target": "Level 1", "notes": ""},
            {"step": 5, "title": "Held lvl 1 — Alle Heldenpunkte auf KK", "target": "Level 1", "notes": ""},
            {"step": 6, "title": "1x Getreidespeicher", "target": "Level 1", "notes": ""},
            {"step": 7, "title": "1x Versteck", "target": "Level 1", "notes": ""},
            {"step": 8, "title": "Alle Getreidefelder auf 1", "target": "Level 1", "notes": ""},
            {"step": 9, "title": "Alle Getreidefelder auf 2", "target": "Level 2", "notes": ""},
            {"step": 10, "title": "Alle Holzfäller auf 1", "target": "Level 1", "notes": ""},
            {"step": 11, "title": "Alle Holzfäller auf 2", "target": "Level 2", "notes": ""},
            {"step": 12, "title": "Alle Lehmgruben auf 1", "target": "Level 1", "notes": ""},
            {"step": 13, "title": "Alle Lehmgruben auf 2", "target": "Level 2", "notes": ""},
            {"step": 14, "title": "Mauer/Palisade/Wall auf 1", "target": "Level 1", "notes": ""},
            {"step": 15, "title": "Hauptgebäude auf 3", "target": "Level 3", "notes": ""},
            {"step": 16, "title": "Botschaft auf 1", "target": "Level 1", "notes": ""},
            {"step": 17, "title": "Marktplatz auf 1", "target": "Level 1", "notes": ""},
            {"step": 18, "title": "Alle Eisenminen auf 1", "target": "Level 1", "notes": ""},
            {"step": 19, "title": "Alle Eisenminen auf 2", "target": "Level 2", "notes": ""},
            {"step": 20, "title": "Versteck auf 3", "target": "Level 3", "notes": ""},
            {"step": 21, "title": "Marktplatz auf 3", "target": "Level 3", "notes": ""},
            {"step": 22, "title": "1x Getreidefeld auf 4", "target": "Level 4", "notes": ""},
            {"step": 23, "title": "1x Holzfäller auf 4", "target": "Level 4", "notes": ""},
            {"step": 24, "title": "1x Lehmgrube auf 4", "target": "Level 4", "notes": ""},
            {"step": 25, "title": "1x Eisenmine auf 4", "target": "Level 4", "notes": ""},
            {"step": 26, "title": "Mauer auf 3", "target": "Level 3", "notes": ""},
            {"step": 27, "title": "Versteck auf 10", "target": "Level 10", "notes": ""},
            {"step": 28, "title": "6x Versteck auf 1", "target": "Level 1", "notes": ""},
            {"step": 29, "title": "Kaserne auf 1", "target": "Level 1", "notes": "Noch keine Truppen bauen!"},
            {"step": 30, "title": "Hauptgebäude auf 7", "target": "Level 7", "notes": ""},
            {"step": 31, "title": "1x Versteck auf 1", "target": "Level 1", "notes": "Ja, richtig, wir bauen noch eins. Insgesamt jetzt 1x Versteck auf 10, und 7x Versteck auf 1"},
            {"step": 32, "title": "Kaserne auf 3", "target": "Level 3", "notes": ""},
            {"step": 33, "title": "Akademie auf 1", "target": "Level 1", "notes": ""},
            {"step": 34, "title": "1x Getreidefeld auf 3", "target": "Level 3", "notes": ""},
            {"step": 35, "title": "3x Eisenmine auf 3", "target": "Level 3", "notes": ""},
            {"step": 36, "title": "1x Lehmgrube auf 3", "target": "Level 3", "notes": ""},
            {"step": 37, "title": "Alle Lehmgruben auf 3", "target": "Level 3", "notes": ""},
            {"step": 38, "title": "1x Getreidefeld auf 3", "target": "Level 3", "notes": ""},
            {"step": 39, "title": "Alle Holzfäller auf 3", "target": "Level 3", "notes": ""},
            {"step": 40, "title": "Alle Getreidefelder auf 3", "target": "Level 3", "notes": ""},
            {"step": 41, "title": "1x Rohstofflager auf 3", "target": "Level 3", "notes": ""},
            {"step": 42, "title": "1x Getreidespeicher auf 3", "target": "Level 3", "notes": ""},
            {"step": 43, "title": "Alle Holzfäller auf 4", "target": "Level 4", "notes": ""},
            {"step": 44, "title": "Alle Lehmgruben auf 4", "target": "Level 4", "notes": ""},
            {"step": 45, "title": "Alle Eisenminen auf 4", "target": "Level 4", "notes": ""},
            {"step": 46, "title": "Alle Getreidefelder auf 4", "target": "Level 4", "notes": ""},
            {"step": 47, "title": "Alle 7 Verstecke auf 3", "target": "Level 3", "notes": ""},
            {"step": 48, "title": "Marktplatz auf 7", "target": "Level 7", "notes": ""},
            {"step": 49, "title": "Hauptgebäude auf 12", "target": "Level 12", "notes": ""},
            {"step": 50, "title": "Schmiede auf 3", "target": "Level 3", "notes": ""},
            {"step": 51, "title": "Akademie auf 5", "target": "Level 5", "notes": ""},
            {"step": 52, "title": "Stall auf 3", "target": "Level 3", "notes": ""},
            {"step": 53, "title": "Akademie auf 10", "target": "Level 10", "notes": "Jetzt erst das 3. Abenteuer erledigen! Es gibt 3 Truppen."},
            {"step": 54, "title": "Werkstatt auf 1", "target": "Level 1", "notes": "In der Kaserne kann jetzt eine weitere Phalanx oder ein weiterer Legionär ausgebildet werden, damit ihr 2x2 Truppen schicken könnt fürs Oasen farmen."},
            {"step": 55, "title": "1x Getreidefeld auf 5", "target": "Level 5", "notes": "ABER NICHT MEHR"},
            {"step": 56, "title": "Rathaus auf 3", "target": "Level 3", "notes": "Ausnahmen Germanen: bei vielen Oasen im 7x7, dann kann man auch mal 10-20 Keulen bauen. Aber geht auch ohne!"},
            {"step": 57, "title": "Rohstofflager auf 8", "target": "Level 8", "notes": ""},
            {"step": 58, "title": "1x Getreidefeld auf 5", "target": "Level 5", "notes": ""},
            {"step": 59, "title": "3x Versteck von 3 auf 7", "target": "Level 7", "notes": "151 KP / Tag"},
            {"step": 60, "title": "4x Versteck von 3 auf 7", "target": "Level 7", "notes": "Nach dem ersten bzw. zweiten Fest muss noch einmal gerechnet werden, ob KP Gebäude weiter hochgezogen werden müssen."},
            {"step": 61, "title": "1x Getreidefeld auf 5", "target": "Level 5", "notes": "In der Reihenfolge Botschaft 6-9, Verstecke auf 10, Aka 11, HG 13. (Wie viel davon und ob überhaupt, ist von Acc zu Acc unterschiedlich/Resabhängig)"},
            {"step": 62, "title": "Getreidespeicher auf 7", "target": "Level 7", "notes": ""},
            {"step": 63, "title": "Botschaft auf 5", "target": "Level 5", "notes": ""},
            {"step": 64, "title": "1. Fest", "target": "", "notes": ""},
            {"step": 65, "title": "1x Getreidefeld auf 5", "target": "Level 5", "notes": ""},
            {"step": 66, "title": "Marktplatz auf 12", "target": "Level 12", "notes": ""},
            {"step": 67, "title": "2. Fest", "target": "", "notes": ""},
            {"step": 68, "title": "2x Getreidefeld auf 5", "target": "Level 5", "notes": ""},
            {"step": 69, "title": "Residenz auf 10", "target": "Level 10", "notes": "188 KP, 250 EW"},
            {"step": 70, "title": "3 Siedler ausbilden", "target": "", "notes": ""},
            {"step": 71, "title": "3. Fest", "target": "", "notes": ""},
            {"step": 72, "title": "Siedeln!", "target": "", "notes": ""},
        ]
    },
    {
        "name": "4 Party Hero Farming — Germanen (T4.6)",
        "tribe": "germanen",
        "description": "Effizienter Siedeln-Guide für Germanen mit 4 Festen. Fokus auf Hero-Raiding & Sim. Ziel: Siedeln in ~105-120h.",
        "steps": [
            {"step": 1, "title": "Held auf kürzestes Abenteuer schicken für Pferd, dann Tiere farmen", "target": "", "notes": "25% Ressproduktions-Bonus aktivieren sobald verfügbar"},
            {"step": 2, "title": "Hauptgebäude auf 1", "target": "Level 1", "notes": ""},
            {"step": 3, "title": "1x Holzfäller auf 2", "target": "Level 2", "notes": ""},
            {"step": 4, "title": "1x Getreidefeld auf 2", "target": "Level 2", "notes": ""},
            {"step": 5, "title": "Versammlungsplatz auf 1", "target": "Level 1", "notes": ""},
            {"step": 6, "title": "1x Lehmgrube auf 2", "target": "Level 2", "notes": "Kosten: 420"},
            {"step": 7, "title": "1x Eisenmine auf 2", "target": "Level 2", "notes": "Kosten: 720. Punkte in Stärke je nach Oasen (0 Oasen: max 2 Punkte, 1-5 Oasen: 8-12, 6+: 12+). Rest in Rohstoffproduktion."},
            {"step": 8, "title": "Gleichmäßiges Wachstum — 1x alle Rohstoffe auf 2", "target": "Level 2", "notes": ""},
            {"step": 9, "title": "Getreidespeicher auf 1", "target": "Level 1", "notes": "Kosten: 270"},
            {"step": 10, "title": "Rohstofflager auf 1", "target": "Level 1", "notes": "Kosten: 420"},
            {"step": 11, "title": "Hauptgebäude auf 3", "target": "Level 3", "notes": "Kosten: 555"},
            {"step": 12, "title": "Getreidespeicher auf 3", "target": "Level 3", "notes": "Kosten: 790"},
            {"step": 13, "title": "Marktplatz auf 1", "target": "Level 1", "notes": "Kosten: 340"},
            {"step": 14, "title": "Marktplatz auf 3", "target": "Level 3", "notes": "Kosten: 990"},
            {"step": 15, "title": "Alle Getreidefelder auf 2", "target": "Level 2", "notes": "Kosten: 3325"},
            {"step": 16, "title": "Botschaft auf 1", "target": "Level 1", "notes": "Kosten: 540"},
            {"step": 17, "title": "Versteck auf 1", "target": "Level 1", "notes": "Kosten: 130"},
            {"step": 18, "title": "Versteck auf 3", "target": "Level 3", "notes": "Kosten: 380"},
            {"step": 19, "title": "Stadtmauer auf 1", "target": "Level 1", "notes": "Kosten: 400"},
            {"step": 20, "title": "Stadtmauer auf 3", "target": "Level 3", "notes": "Kosten: 1170"},
            {"step": 21, "title": "Alle Holzfäller auf 2", "target": "Level 2", "notes": "Kosten: 1995"},
            {"step": 22, "title": "Alle Lehmgruben auf 2", "target": "Level 2", "notes": "Kosten: 2010. Oasen raiden bis Laufzeit 1h+. Dann Abenteuer 2 (Res-Beute) in Betracht ziehen (~2300 Res)"},
            {"step": 23, "title": "Alle Eisenminen auf 2", "target": "Level 2", "notes": "Kosten: 2175"},
            {"step": 24, "title": "Vollständige Wirtschaft — alle Rohstoffe auf 2", "target": "Level 2", "notes": "Kosten: 2400"},
            {"step": 25, "title": "Bevölkerung auf 50", "target": "50 EW", "notes": "Kosten: 1500"},
            {"step": 26, "title": "Rohstofflager auf 3", "target": "Level 3", "notes": "Kosten: 1220"},
            {"step": 27, "title": "Kaserne auf 1", "target": "Level 1", "notes": "Kosten: 730"},
            {"step": 28, "title": "1x Holzfäller auf 4", "target": "Level 4", "notes": "Kosten: 1860. Oasen weiter raiden bis 2h+ Laufzeit, dann fast alle Punkte in Ressproduktion (Buch der Weisheit aus Abenteuer 6)"},
            {"step": 29, "title": "1x Getreidefeld auf 4", "target": "Level 4", "notes": "Kosten: 1860"},
            {"step": 30, "title": "1x Lehmgrube auf 4", "target": "Level 4", "notes": "Kosten: 1870"},
            {"step": 31, "title": "1x Eisenmine auf 4", "target": "Level 4", "notes": "Kosten: 2015"},
            {"step": 32, "title": "Gleichmäßiges Wachstum — 1x alle auf 4", "target": "Level 4", "notes": "Kosten: 600"},
            {"step": 33, "title": "Versteck auf 6", "target": "Level 6", "notes": "Kosten: 1065"},
            {"step": 34, "title": "Hauptgebäude auf 7", "target": "Level 7", "notes": "Kosten: 2395"},
            {"step": 35, "title": "Kulturpunktproduktion auf 50", "target": "50 KP", "notes": "Kosten: 1500"},
            {"step": 36, "title": "Kaserne auf 3", "target": "Level 3", "notes": "Kosten: 2135"},
            {"step": 37, "title": "Akademie auf 1", "target": "Level 1", "notes": "Kosten: 510"},
            {"step": 38, "title": "1x Getreidefeld auf 3", "target": "Level 3", "notes": "Kosten: 695"},
            {"step": 39, "title": "Schmiede auf 1", "target": "Level 1", "notes": "Kosten: 1090"},
            {"step": 40, "title": "Alle Eisenminen auf 3", "target": "Level 3", "notes": "Kosten: 2265"},
            {"step": 41, "title": "Bevölkerung auf 100", "target": "100 EW", "notes": "Kosten: 3000"},
            {"step": 42, "title": "Alle Getreidefelder auf 3", "target": "Level 3", "notes": "Kosten: 2780"},
            {"step": 43, "title": "Alle Holzfäller auf 3", "target": "Level 3", "notes": "Kosten: 2085"},
            {"step": 44, "title": "Alle Lehmgruben auf 3 — ZIEL: hier in max. 2h sein!", "target": "Level 3", "notes": "Kosten: 2100"},
            {"step": 45, "title": "Versteck auf 10", "target": "Level 10", "notes": "Kosten: 3430"},
            {"step": 46, "title": "Marktplatz auf 7", "target": "Level 7", "notes": "Kosten: 4290"},
            {"step": 47, "title": "Residenz auf 1", "target": "Level 1", "notes": "Kosten: 1570"},
            {"step": 48, "title": "Vollständige Wirtschaft — alle Rohstoffe auf 4 — ZIEL: hier in max. 12h!", "target": "Level 4", "notes": "Kosten: 16610"},
            {"step": 49, "title": "8x Verstecke auf 3", "target": "Level 3", "notes": "Kosten: 4080"},
            {"step": 50, "title": "Alle Getreidefelder auf 5", "target": "Level 5", "notes": "Kosten: 9725"},
            {"step": 51, "title": "Alle Lehmgruben auf 5", "target": "Level 5", "notes": "Kosten: 7760"},
            {"step": 52, "title": "Alle Holzfäller auf 5", "target": "Level 5", "notes": "Kosten: 7780"},
            {"step": 53, "title": "Alle Eisenminen auf 5", "target": "Level 5", "notes": "Kosten: 8400"},
            {"step": 54, "title": "Bevölkerung auf 150", "target": "150 EW", "notes": "Kosten: 4500"},
            {"step": 55, "title": "Hauptgebäude auf 8", "target": "Level 8", "notes": "Kosten: 1075"},
            {"step": 56, "title": "Hauptgebäude auf 12", "target": "Level 12", "notes": "Kosten: 8235"},
            {"step": 57, "title": "Akademie auf 10", "target": "Level 10", "notes": "Kosten: 19165"},
            {"step": 58, "title": "Werkstatt auf 1", "target": "Level 1", "notes": "Kosten: 1895"},
            {"step": 59, "title": "Rathaus auf 1", "target": "Level 1", "notes": "Kosten: 4220"},
            {"step": 60, "title": "Marktplatz auf 10", "target": "Level 10", "notes": "Kosten: 7500. ZIEL: Fest 1 in max. 48h!"},
            {"step": 61, "title": "Getreidespeicher auf 7", "target": "Level 7", "notes": "Kosten: 3415"},
            {"step": 62, "title": "Kulturpunktproduktion auf 150", "target": "150 KP", "notes": "Kosten: 4500. Verstecke ggf. auf 7 upgraden um fehlende KP zu kompensieren!"},
            {"step": 63, "title": "Rohstofflager auf 7", "target": "Level 7", "notes": "Kosten: 5295"},
            {"step": 64, "title": "Residenz auf 3", "target": "Level 3", "notes": "Kosten: 4585"},
            {"step": 65, "title": "Rohstofflager auf 8", "target": "Level 8", "notes": "Kosten: 2360"},
            {"step": 66, "title": "🎉 1. Fest feiern!", "target": "", "notes": "Kosten: 20330"},
            {"step": 67, "title": "Marktplatz auf 12", "target": "Level 12", "notes": "Kosten: 9155"},
            {"step": 68, "title": "Botschaft auf 6", "target": "Level 6", "notes": "Kosten: 6015"},
            {"step": 69, "title": "Schmiede auf 3", "target": "Level 3", "notes": "Kosten: 2570"},
            {"step": 70, "title": "Stall auf 3", "target": "Level 3", "notes": "Kosten: 2825"},
            {"step": 71, "title": "Residenz auf 7", "target": "Level 7", "notes": "Kosten: 19510"},
            {"step": 72, "title": "Residenz auf 8", "target": "Level 8", "notes": "Kosten: 8840"},
            {"step": 73, "title": "Bevölkerung auf 250", "target": "250 EW", "notes": "Kosten: 6000"},
            {"step": 74, "title": "🎉 2. Fest feiern!", "target": "", "notes": "Kosten: 20330"},
            {"step": 75, "title": "Residenz auf 10", "target": "Level 10", "notes": "Kosten: 25795"},
            {"step": 76, "title": "Siedler ausbilden (1/3)", "target": "", "notes": "Kosten: 20000"},
            {"step": 77, "title": "🎉 3. Fest feiern!", "target": "", "notes": "Kosten: 20330"},
            {"step": 78, "title": "Siedler ausbilden (2+3/3)", "target": "", "notes": "Kosten: 40000"},
            {"step": 79, "title": "🎉 4. Fest feiern!", "target": "", "notes": "Kosten: 20330"},
            {"step": 80, "title": "🎯 Siedeln! (3000 Res für Gründung nicht vergessen)", "target": "", "notes": "Erwartete Siedelzeit: ~105-120h"},
        ]
    }
]
