PRESET_BLUEPRINTS = [
    {
        "name": "Siedeln Route — Standard",
        "tribe": "alle",
        "description": "Klassische Siedeln-Route für einen effizienten Start ins Runde. Ziel: 3. Dorf so schnell wie möglich.",
        "steps": [
            {"step": 1, "title": "Das erste Abenteuer machen", "target": "", "notes": ""},
            {"step": 2, "title": "1x Lehmgrube", "target": "Level 2", "notes": "von 1 auf 2"},
            {"step": 3, "title": "1x Eisenmine", "target": "Level 2", "notes": ""},
            {"step": 4, "title": "1x Rohstofflager", "target": "Level 1", "notes": ""},
            {"step": 5, "title": "Held lvl 1 — Alle Heldenpunkte auf KK", "target": "Level 1", "notes": ""},
            {"step": 6, "title": "1x Getreidespeicher", "target": "Level 1", "notes": ""},
            {"step": 7, "title": "1x Versteck", "target": "Level 1", "notes": ""},
            {"step": 8, "title": "Alle Getreidefelder auf 1", "target": "Level 1", "notes": ""},
            {"step": 9, "title": "Alle Getreidefelder auf 2", "target": "Level 2", "notes": ""},
            {"step": 10, "title": "Alle Holzfäller auf 1", "target": "Level 1", "notes": ""},
            {"step": 11, "title": "Alle Holzfäller auf 2", "target": "Level 2", "notes": ""},
            {"step": 12, "title": "Alle Lehmgruben auf 1", "target": "Level 1", "notes": ""},
            {"step": 13, "title": "Alle Lehmgruben auf 2", "target": "Level 2", "notes": ""},
            {"step": 14, "title": "Mauer/Palisade/Wall auf 1", "target": "Level 1", "notes": ""},
            {"step": 15, "title": "Hauptgebäude auf 3", "target": "Level 3", "notes": ""},
            {"step": 16, "title": "Botschaft auf 1", "target": "Level 1", "notes": ""},
            {"step": 17, "title": "Marktplatz auf 1", "target": "Level 1", "notes": ""},
            {"step": 18, "title": "Alle Eisenminen auf 1", "target": "Level 1", "notes": ""},
            {"step": 19, "title": "Alle Eisenminen auf 2", "target": "Level 2", "notes": ""},
            {"step": 20, "title": "Versteck auf 3", "target": "Level 3", "notes": ""},
            {"step": 21, "title": "Marktplatz auf 3", "target": "Level 3", "notes": ""},
            {"step": 22, "title": "1x Getreidefeld auf 4", "target": "Level 4", "notes": ""},
            {"step": 23, "title": "1x Holzfäller auf 4", "target": "Level 4", "notes": ""},
            {"step": 24, "title": "1x Lehmgrube auf 4", "target": "Level 4", "notes": ""},
            {"step": 25, "title": "1x Eisenmine auf 4", "target": "Level 4", "notes": ""},
            {"step": 26, "title": "Mauer auf 3", "target": "Level 3", "notes": ""},
            {"step": 27, "title": "Versteck auf 10", "target": "Level 10", "notes": ""},
            {"step": 28, "title": "6x Versteck auf 1", "target": "Level 1", "notes": ""},
            {"step": 29, "title": "Kaserne auf 1", "target": "Level 1", "notes": "Noch keine Truppen bauen!"},
            {"step": 30, "title": "Hauptgebäude auf 7", "target": "Level 7", "notes": ""},
            {"step": 31, "title": "1x Versteck auf 1", "target": "Level 1", "notes": "Ja, richtig, wir bauen noch eins. Insgesamt jetzt 1x Versteck auf 10, und 7x Versteck auf 1"},
            {"step": 32, "title": "Kaserne auf 3", "target": "Level 3", "notes": ""},
            {"step": 33, "title": "Akademie auf 1", "target": "Level 1", "notes": ""},
            {"step": 34, "title": "1x Getreidefeld auf 3", "target": "Level 3", "notes": ""},
            {"step": 35, "title": "3x Eisenmine auf 3", "target": "Level 3", "notes": ""},
            {"step": 36, "title": "1x Lehmgrube auf 3", "target": "Level 3", "notes": ""},
            {"step": 37, "title": "Alle Lehmgruben auf 3", "target": "Level 3", "notes": ""},
            {"step": 38, "title": "1x Getreidefeld auf 3", "target": "Level 3", "notes": ""},
            {"step": 39, "title": "Alle Holzfäller auf 3", "target": "Level 3", "notes": ""},
            {"step": 40, "title": "Alle Getreidefelder auf 3", "target": "Level 3", "notes": ""},
            {"step": 41, "title": "1x Rohstofflager auf 3", "target": "Level 3", "notes": ""},
            {"step": 42, "title": "1x Getreidespeicher auf 3", "target": "Level 3", "notes": ""},
            {"step": 43, "title": "Alle Holzfäller auf 4", "target": "Level 4", "notes": ""},
            {"step": 44, "title": "Alle Lehmgruben auf 4", "target": "Level 4", "notes": ""},
            {"step": 45, "title": "Alle Eisenminen auf 4", "target": "Level 4", "notes": ""},
            {"step": 46, "title": "Alle Getreidefelder auf 4", "target": "Level 4", "notes": ""},
            {"step": 47, "title": "Alle 7 Verstecke auf 3", "target": "Level 3", "notes": ""},
            {"step": 48, "title": "Marktplatz auf 7", "target": "Level 7", "notes": ""},
            {"step": 49, "title": "Hauptgebäude auf 12", "target": "Level 12", "notes": ""},
            {"step": 50, "title": "Schmiede auf 3", "target": "Level 3", "notes": ""},
            {"step": 51, "title": "Akademie auf 5", "target": "Level 5", "notes": ""},
            {"step": 52, "title": "Stall auf 3", "target": "Level 3", "notes": ""},
            {"step": 53, "title": "Akademie auf 10", "target": "Level 10", "notes": "Jetzt erst das 3. Abenteuer erledigen! Es gibt 3 Truppen."},
            {"step": 54, "title": "Werkstatt auf 1", "target": "Level 1", "notes": "In der Kaserne kann jetzt eine weitere Phalanx oder ein weiterer Legionär ausgebildet werden, damit ihr 2x2 Truppen schicken könnt fürs Oasen farmen."},
            {"step": 55, "title": "1x Getreidefeld auf 5", "target": "Level 5", "notes": "ABER NICHT MEHR"},
            {"step": 56, "title": "Rathaus auf 3", "target": "Level 3", "notes": "Ausnahmen Germanen: bei vielen Oasen im 7x7, dann kann man auch mal 10-20 Keulen bauen. Aber geht auch ohne!"},
            {"step": 57, "title": "Rohstofflager auf 8", "target": "Level 8", "notes": ""},
            {"step": 58, "title": "1x Getreidefeld auf 5", "target": "Level 5", "notes": ""},
            {"step": 59, "title": "3x Versteck von 3 auf 7", "target": "Level 7", "notes": "151 KP / Tag"},
            {"step": 60, "title": "4x Versteck von 3 auf 7", "target": "Level 7", "notes": "Nach dem ersten bzw. zweiten Fest muss noch einmal gerechnet werden, ob KP Gebäude weiter hochgezogen werden müssen."},
            {"step": 61, "title": "1x Getreidefeld auf 5", "target": "Level 5", "notes": "In der Reihenfolge Botschaft 6-9, Verstecke auf 10, Aka 11, HG 13. (Wie viel davon und ob überhaupt, ist von Acc zu Acc unterschiedlich/Resabhängig)"},
            {"step": 62, "title": "Getreidespeicher auf 7", "target": "Level 7", "notes": ""},
            {"step": 63, "title": "Botschaft auf 5", "target": "Level 5", "notes": ""},
            {"step": 64, "title": "1. Fest", "target": "", "notes": ""},
            {"step": 65, "title": "1x Getreidefeld auf 5", "target": "Level 5", "notes": ""},
            {"step": 66, "title": "Marktplatz auf 12", "target": "Level 12", "notes": ""},
            {"step": 67, "title": "2. Fest", "target": "", "notes": ""},
            {"step": 68, "title": "2x Getreidefeld auf 5", "target": "Level 5", "notes": ""},
            {"step": 69, "title": "Residenz auf 10", "target": "Level 10", "notes": "188 KP, 250 EW"},
            {"step": 70, "title": "3 Siedler ausbilden", "target": "", "notes": ""},
            {"step": 71, "title": "3. Fest", "target": "", "notes": ""},
            {"step": 72, "title": "Siedeln!", "target": "", "notes": ""},
        ]
    }
]
